version: '3.4'

services:
  noderunningondocker:
    image: noderunningondocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 91:91
